In [15]:
import re
import numpy as np
import pandas as pd
from bs4 import BeautifulSoup
pd.set_option("display.max_colwidth",200)

In [16]:
questions_df=pd.read_csv(r"C:\Users\shrishti\Videos\Captures\Auto stack exchange\Module 13\Questions.csv", encoding="Latin-1")
print("shape=>",questions_df.shape)
questions_df.head()

shape=> (85085, 6)

,Id,OwnerUserId,CreationDate,Score,Title,Body
0,6,5.0,2010-07-19T19:14:44Z,272,The Two Cultures: statistics vs. machine learning?,"<p>Last year, I read a blog post from <a href=""http://anyall.org/"">Brendan O'Connor</a> entitled <a href=""http://anyall.org/blog/2008/12/statistics-vs-machine-learning-fight/"">""Statistics vs. Mach..."
1,21,59.0,2010-07-19T19:24:36Z,4,Forecasting demographic census,<p>What are some of the ways to forecast demographic census with some validation and calibration techniques?</p>\n\n<p>Some of the concerns:</p>\n\n<ul>\n<li>Census blocks vary in sizes as rural\n...
2,22,66.0,2010-07-19T19:25:39Z,208,Bayesian and frequentist reasoning in plain English,<p>How would you describe in plain English the characteristics that distinguish Bayesian from Frequentist reasoning?</p>\n
3,31,13.0,2010-07-19T19:28:44Z,138,What is the meaning of p values and t values in statistical tests?,"<p>After taking a statistics course and then trying to help fellow students, I noticed one subject that inspires much head-desk banging is interpreting the results of statistical hypothesis tests...."
4,36,8.0,2010-07-19T19:31:47Z,58,Examples for teaching: Correlation does not mean causation,"<p>There is an old saying: ""Correlation does not mean causation"". When I teach, I tend to use the following standard examples to illustrate this point:</p>\n\n<ol>\n<li>number of storks and birth ..."

In [17]:
tags_df=pd.read_csv(r"C:\Users\shrishti\Videos\Captures\Auto stack exchange\Module 13\Tags.csv", encoding="Latin-1")
print("shape=>",tags_df.shape)
tags_df.head()

shape=> (244228, 2)

   Id            Tag
0   1       bayesian
1   1          prior
2   1    elicitation
3   2  distributions
4   2      normality

In [18]:
import re

def basic_clean(text):
    text = re.sub(r"<.*?>", " ", text)   # remove HTML tags (FAST)
    text = re.sub("[^a-zA-Z]", " ", text)
    text = text.lower()
    text = re.sub(r"\s+", " ", text)
    return text

questions_df["cleaned_text"] = questions_df["Body"].fillna("").apply(basic_clean)

In [19]:
questions_df["Body"][1]

"<p>What are some of the ways to forecast demographic census with some validation and calibration techniques?</p>\n\n<p>Some of the concerns:</p>\n\n<ul>\n<li>Census blocks vary in sizes as rural\nareas are a lot larger than condensed\nurban areas. Is there a need to account for the area size difference?</li>\n<li>if let's say I have census data\ndating back to 4 - 5 census periods,\nhow far can i forecast it into the\nfuture?</li>\n<li>if some of the census zone change\nlightly in boundaries, how can i\naccount for that change?</li>\n<li>What are the methods to validate\ncensus forecasts? for example, if i\nhave data for existing 5 census\nperiods, should I model the first 3\nand test it on the latter two? or is\nthere another way?</li>\n<li>what's the state of practice in\nforecasting census data, and what are\nsome of the state of the art methods?</li>\n</ul>\n"

In [20]:
questions_df["cleaned_text"][1]

' what are some of the ways to forecast demographic census with some validation and calibration techniques some of the concerns census blocks vary in sizes as rural areas are a lot larger than condensed urban areas is there a need to account for the area size difference if let s say i have census data dating back to census periods how far can i forecast it into the future if some of the census zone change lightly in boundaries how can i account for that change what are the methods to validate census forecasts for example if i have data for existing census periods should i model the first and test it on the latter two or is there another way what s the state of practice in forecasting census data and what are some of the state of the art methods '

In [21]:
tags_df.head()

   Id            Tag
0   1       bayesian
1   1          prior
2   1    elicitation
3   2  distributions
4   2      normality

In [22]:
len(tags_df["Tag"].unique())

1315

In [23]:
tags_df["Tag"].value_counts()

Tag
r                       13236
regression              10959
machine-learning         6089
time-series              5559
probability              4217
                        ...
fmincon                     1
doc2vec                     1
sympy                       1
adversarial-boosting        1
corpus-linguistics          1
Name: count, Length: 1315, dtype: int64

In [24]:
tags_df["Tag"]=tags_df["Tag"].apply(lambda x: re.sub("-", " ", x))

In [25]:
tags_df=tags_df.groupby('Id').apply(lambda x:x['Tag'].values).reset_index(name='tags')

C:\Users\shrishti\AppData\Local\Temp\ipykernel_11856\105671489.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  tags_df=tags_df.groupby('Id').apply(lambda x:x['Tag'].values).reset_index(name='tags')

In [26]:
tags_df.head()

   Id                                       tags
0   1             [bayesian, prior, elicitation]
1   2                 [distributions, normality]
2   3                    [software, open source]
3   4  [distributions, statistical significance]
4   6                         [machine learning]

In [27]:
df=pd.merge(questions_df, tags_df, how='inner',on='Id')

In [28]:
df=df[['Id','Body','cleaned_text','tags']]
print("shape=>", df.shape)
df.head()

shape=> (85085, 4)

,Id,Body,cleaned_text,tags
0,6,"<p>Last year, I read a blog post from <a href=""http://anyall.org/"">Brendan O'Connor</a> entitled <a href=""http://anyall.org/blog/2008/12/statistics-vs-machine-learning-fight/"">""Statistics vs. Mach...",last year i read a blog post from brendan o connor entitled statistics vs machine learning fight that discussed some of the differences between the two fields andrew gelman responded favorably to...,[machine learning]
1,21,<p>What are some of the ways to forecast demographic census with some validation and calibration techniques?</p>\n\n<p>Some of the concerns:</p>\n\n<ul>\n<li>Census blocks vary in sizes as rural\n...,what are some of the ways to forecast demographic census with some validation and calibration techniques some of the concerns census blocks vary in sizes as rural areas are a lot larger than cond...,"[forecasting, population, census]"
2,22,<p>How would you describe in plain English the characteristics that distinguish Bayesian from Frequentist reasoning?</p>\n,how would you describe in plain english the characteristics that distinguish bayesian from frequentist reasoning,"[bayesian, frequentist]"
3,31,"<p>After taking a statistics course and then trying to help fellow students, I noticed one subject that inspires much head-desk banging is interpreting the results of statistical hypothesis tests....",after taking a statistics course and then trying to help fellow students i noticed one subject that inspires much head desk banging is interpreting the results of statistical hypothesis tests it ...,"[hypothesis testing, t test, p value, interpretation, intuition]"
4,36,"<p>There is an old saying: ""Correlation does not mean causation"". When I teach, I tend to use the following standard examples to illustrate this point:</p>\n\n<ol>\n<li>number of storks and birth ...",there is an old saying correlation does not mean causation when i teach i tend to use the following standard examples to illustrate this point number of storks and birth rate in denmark number of...,"[correlation, teaching]"

In [29]:
freq={}
for i in df['tags']:
    for j in i:
        if j in freq.keys():
          freq[j]=freq[j]+1
        else:
            freq[j]=1

In [30]:
freq=dict(sorted(freq.items(), key=lambda x:x[1],reverse=True))

In [31]:
freq.items()

dict_items([('r', 13236), ('regression', 10959), ('machine learning', 6089), ('time series', 5559), ('probability', 4217), ('hypothesis testing', 3869), ('self study', 3732), ('distributions', 3501), ('logistic', 3316), ('classification', 2881), ('correlation', 2871), ('statistical significance', 2666), ('bayesian', 2656), ('anova', 2505), ('normal distribution', 2181), ('multiple regression', 2054), ('mixed model', 1998), ('clustering', 1952), ('neural networks', 1897), ('mathematical statistics', 1888), ('confidence interval', 1776), ('categorical data', 1703), ('generalized linear model', 1614), ('variance', 1576), ('data visualization', 1549), ('estimation', 1533), ('forecasting', 1422), ('t test', 1418), ('pca', 1395), ('sampling', 1363), ('cross validation', 1344), ('repeated measures', 1335), ('spss', 1296), ('svm', 1283), ('chi squared', 1261), ('maximum likelihood', 1209), ('predictive models', 1189), ('multivariate analysis', 1116), ('survival', 1081), ('references', 1076), ('data transformation', 1057), ('modeling', 1055), ('p value', 1040), ('feature selection', 997), ('econometrics', 989), ('panel data', 966), ('python', 955), ('data mining', 950), ('interaction', 946), ('matlab', 941), ('linear model', 937), ('binomial', 935), ('random forest', 935), ('nonparametric', 922), ('arima', 917), ('least squares', 898), ('optimization', 898), ('model selection', 876), ('standard deviation', 866), ('poisson', 865), ('interpretation', 860), ('sample size', 847), ('mean', 842), ('stata', 842), ('dataset', 840), ('conditional probability', 837), ('prediction', 832), ('multiple comparisons', 825), ('bootstrap', 814), ('experiment design', 780), ('random variable', 745), ('autocorrelation', 678), ('simulation', 676), ('covariance', 666), ('multilevel analysis', 663), ('pdf', 654), ('missing data', 652), ('expected value', 645), ('regression coefficients', 643), ('factor analysis', 642), ('mcmc', 635), ('outliers', 629), ('standard error', 629), ('inference', 625), ('ordinal', 624), ('survey', 617), ('deep learning', 600), ('cart', 593), ('residuals', 582), ('binary data', 570), ('random effects model', 569), ('goodness of fit', 567), ('model', 567), ('terminology', 551), ('stochastic processes', 530), ('nonlinear regression', 514), ('cox model', 510), ('monte carlo', 504), ('proportion', 503), ('algorithms', 500), ('sas', 496), ('lasso', 490), ('normalization', 484), ('heteroscedasticity', 483), ('error', 481), ('independence', 480), ('meta analysis', 480), ('multinomial', 480), ('k means', 465), ('lmer', 463), ('sample', 450), ('markov process', 445), ('scikit learn', 440), ('multicollinearity', 438), ('text mining', 432), ('aic', 431), ('descriptive statistics', 430), ('spatial', 429), ('assumptions', 418), ('matrix', 413), ('likelihood', 407), ('dimensionality reduction', 407), ('sem', 405), ('bias', 396), ('fixed effects model', 391), ('effect size', 375), ('logit', 374), ('r squared', 372), ('normality', 371), ('lme4', 371), ('convergence', 370), ('likert', 366), ('power analysis', 365), ('glmm', 359), ('negative binomial', 358), ('roc', 358), ('fitting', 357), ('computational statistics', 348), ('count data', 347), ('random generation', 345), ('prior', 340), ('summary statistics', 338), ('ranking', 338), ('stationarity', 337), ('natural language', 335), ('covariance matrix', 332), ('skewness', 325), ('kernel trick', 321), ('gamma distribution', 319), ('naive bayes', 318), ('continuous data', 317), ('regularization', 317), ('hidden markov model', 314), ('reliability', 314), ('power', 312), ('gaussian process', 310), ('group differences', 309), ('autoregressive', 307), ('biostatistics', 306), ('distance', 304), ('garch', 302), ('ancova', 300), ('causality', 300), ('standardization', 300), ('validation', 296), ('small sample', 295), ('exponential', 295), ('quantiles', 293), ('posterior', 291), ('var', 289), ('curve fitting', 288), ('post hoc', 284), ('kernel smoothing', 284), ('robust', 282), ('average', 277), ('gradient descent', 277), ('odds ratio', 275), ('lognormal', 275), ('median', 273), ('bayes', 273), ('seasonality', 270), ('expectation maximization', 270), ('uniform', 268), ('cointegration', 268), ('large data', 266), ('kolmogorov smirnov', 266), ('wilcoxon', 266), ('discrete data', 266), ('conv neural network', 264), ('gaussian mixture', 261), ('histogram', 260), ('non independent', 259), ('entropy', 259), ('pearson', 258), ('excel', 257), ('trend', 256), ('linear', 256), ('arma', 255), ('contingency tables', 253), ('joint distribution', 253), ('pattern recognition', 253), ('manova', 252), ('cdf', 250), ('scales', 248), ('unbalanced classes', 247), ('conditional expectation', 245), ('unbiased estimator', 245), ('mixture', 244), ('measurement error', 243), ('mann whitney u test', 242), ('boosting', 240), ('likelihood ratio', 238), ('data imputation', 238), ('hierarchical bayesian', 237), ('k nearest neighbour', 236), ('central limit theorem', 236), ('asymptotics', 236), ('discriminant analysis', 234), ('caret', 233), ('poisson regression', 233), ('unsupervised learning', 232), ('paired comparisons', 232), ('accuracy', 231), ('permutation', 231), ('graphical model', 231), ('psychometrics', 228), ('ridge regression', 228), ('instrumental variables', 227), ('image processing', 227), ('probit', 226), ('basic concepts', 226), ('similarities', 225), ('multiple imputation', 223), ('distance functions', 222), ('population', 219), ('overfitting', 217), ('predictor', 215), ('gibbs', 215), ('information theory', 212), ('recommender system', 206), ('feature construction', 206), ('estimators', 205), ('degrees of freedom', 205), ('glmnet', 202), ('jags', 201), ('finance', 200), ('gam', 199), ('epidemiology', 198), ('beta distribution', 198), ('proof', 198), ('moments', 198), ('notation', 196), ('linear algebra', 193), ('model comparison', 193), ('bayesian network', 192), ('nonlinear', 191), ('smoothing', 191), ('supervised learning', 191), ('approximation', 187), ('prediction interval', 185), ('cross correlation', 185), ('lme', 183), ('nested', 183), ('svd', 182), ('kalman filter', 180), ('fishers exact', 180), ('bernoulli distribution', 179), ('precision recall', 178), ('libsvm', 177), ('gee', 177), ('measurement', 177), ('latent variable', 177), ('loss functions', 176), ('contrasts', 176), ('zero inflation', 174), ('frequency', 174), ('splines', 173), ('logarithm', 172), ('t distribution', 172), ('auc', 172), ('censoring', 172), ('unit root', 172), ('resampling', 171), ('kruskal wallis', 170), ('intuition', 168), ('uncertainty', 165), ('order statistics', 165), ('hazard', 162), ('regression strategies', 162), ('mediation', 162), ('f test', 162), ('weka', 162), ('graph theory', 160), ('ensemble', 159), ('confirmatory factor', 157), ('definition', 156), ('glmer', 156), ('parametric', 155), ('copula', 155), ('combinatorics', 155), ('polynomial', 154), ('lm', 153), ('performance', 153), ('marginal', 153), ('software', 151), ('signal processing', 151), ('mutual information', 150), ('weighted regression', 150), ('propensity scores', 148), ('bonferroni', 148), ('multi class', 148), ('matching', 147), ('reinforcement learning', 145), ('diagnostic', 145), ('frequentist', 144), ('non stationary', 144), ('methodology', 142), ('genetics', 141), ('pymc', 141), ('dirichlet distribution', 140), ('bic', 139), ('stepwise regression', 139), ('metropolis hastings', 138), ('gbm', 138), ('analysis', 138), ('theory', 137), ('kullback leibler', 137), ('eigenvalues', 136), ('intraclass correlation', 135), ('inter rater', 134), ('paired data', 134), ('difference in difference', 133), ('metric', 132), ('hierarchical', 132), ('error propagation', 131), ('scatterplot', 131), ('multivariate regression', 131), ('interpolation', 130), ('quantile regression', 130), ('multidimensional scaling', 130), ('aggregation', 128), ('mse', 128), ('reporting', 128), ('hierarchical clustering', 128), ('weibull', 128), ('qq plot', 127), ('multivariate normal', 127), ('parameterization', 126), ('train', 126), ('change point', 125), ('irt', 124), ('matrix decomposition', 123), ('sparse', 123), ('topic models', 123), ('bioinformatics', 123), ('bivariate', 122), ('decision theory', 121), ('exponential smoothing', 121), ('lags', 120), ('backpropagation', 120), ('kurtosis', 120), ('poisson process', 119), ('state space models', 119), ('percentage', 119), ('randomization', 119), ('endogeneity', 118), ('ratio', 117), ('weighted mean', 116), ('z test', 116), ('eda', 116), ('spearman', 116), ('exponential family', 115), ('confidence', 115), ('nlme', 114), ('statistical learning', 114), ('probability inequalities', 114), ('false discovery rate', 113), ('networks', 112), ('convolution', 112), ('markov chain', 111), ('extreme value', 111), ('clinical trials', 110), ('autoencoders', 110), ('generalized least squares', 110), ('pls', 109), ('ecology', 109), ('boxplot', 109), ('hyperparameter', 109), ('sums of squares', 109), ('stratification', 109), ('learning', 108), ('teaching', 107), ('ab test', 107), ('conjugate prior', 106), ('sufficient statistics', 106), ('confounding', 106), ('consistency', 106), ('treatment effect', 105), ('ggplot2', 105), ('covariate', 104), ('bugs', 102), ('computer vision', 102), ('online', 100), ('coefficient', 99), ('randomness', 99), ('games', 98), ('granger causality', 98), ('weighted sampling', 98), ('kaplan meier', 97), ('high dimensional', 97), ('elastic net', 97), ('threshold', 96), ('sample mean', 94), ('lstm', 94), ('augmented dickey fuller', 94), ('fisher information', 94), ('rms', 93), ('pooling', 92), ('time varying covariate', 92), ('rpart', 92), ('spearman rho', 92), ('vecm', 92), ('hypergeometric', 92), ('moving average', 92), ('bounds', 92), ('maximum', 91), ('scores', 91), ('fourier transform', 90), ('integral', 90), ('overdispersion', 90), ('scipy', 90), ('type i errors', 90), ('power law', 89), ('residual analysis', 89), ('mathematics', 88), ('deviance', 88), ('binning', 88), ('interval', 87), ('psychology', 87), ('tukey hsd', 87), ('calibration', 87), ('rank correlation', 87), ('nominal', 86), ('intercept', 86), ('model evaluation', 86), ('information retrieval', 85), ('cross section', 85), ('partial correlation', 84), ('dice', 84), ('lme4 nlme', 84), ('z score', 84), ('genetic algorithms', 82), ('truncation', 81), ('partitioning', 81), ('weighted data', 81), ('quality control', 81), ('kappa', 81), ('importance', 80), ('log linear', 79), ('empirical', 79), ('function', 79), ('parameter optimization', 78), ('data preprocessing', 78), ('generalized moments', 77), ('association rules', 77), ('rnn', 77), ('social network', 77), ('sensitivity', 76), ('point estimation', 76), ('bagging', 76), ('matrix inverse', 76), ('java', 75), ('cohens d', 75), ('spectral analysis', 75), ('risk', 75), ('odds', 75), ('out of sample', 74), ('history', 74), ('association measure', 74), ('quadratic form', 74), ('random walk', 74), ('sequence analysis', 74), ('rbm', 74), ('filter', 74), ('centering', 73), ('control', 73), ('clustered standard errors', 73), ('link function', 73), ('maximum entropy', 73), ('deep belief networks', 72), ('artificial intelligence', 72), ('dirichlet process', 72), ('rare events', 72), ('validity', 71), ('mode', 71), ('confusion matrix', 71), ('meta regression', 71), ('pareto distribution', 70), ('winbugs', 70), ('observational study', 70), ('point process', 70), ('method comparison', 69), ('cluster sample', 68), ('circular statistics', 68), ('case control study', 68), ('segmentation', 68), ('shrinkage', 68), ('sequential analysis', 67), ('mcnemar test', 67), ('scoring', 67), ('kendall tau', 67), ('intervention analysis', 67), ('2sls', 66), ('fisher', 65), ('tobit regression', 65), ('loess', 65), ('volatility forecasting', 64), ('mgcv', 64), ('ranks', 64), ('beta binomial', 63), ('dynamic regression', 63), ('inferential statistics', 63), ('stan', 63), ('mice', 62), ('delta method', 62), ('rating', 62), ('iid', 61), ('moderation', 61), ('correspondence analysis', 61), ('anomaly detection', 61), ('method of moments', 61), ('equivalence', 61), ('relative risk', 61), ('hausman', 60), ('euclidean', 60), ('marketing', 60), ('noise', 60), ('minimum', 60), ('efficiency', 60), ('ordered logit', 60), ('numerical integration', 60), ('beta regression', 59), ('identifiability', 59), ('structural change', 59), ('geostatistics', 58), ('vif', 58), ('signal detection', 58), ('derivative', 58), ('traminer', 57), ('variational bayes', 57), ('tensorflow', 57), ('growth model', 57), ('coefficient of variation', 57), ('subset', 56), ('canonical correlation', 56), ('offset', 56), ('latent class', 56), ('spatio temporal', 55), ('multilabel', 55), ('adjustment', 55), ('cronbachs alpha', 55), ('white noise', 54), ('queueing', 54), ('credible interval', 54), ('composite', 53), ('philosophical', 53), ('statsmodels', 52), ('perceptron', 52), ('variogram', 52), ('statistical', 51), ('importance sampling', 51), ('variability', 51), ('mgf', 51), ('nls', 50), ('penalized', 50), ('numerics', 50), ('self organizing maps', 50), ('weights', 50), ('word2vec', 50), ('lsa', 49), ('finite population', 49), ('particle filter', 49), ('amos', 49), ('nonparametric bayes', 49), ('sensitivity analysis', 48), ('specificity', 48), ('education', 48), ('wishart', 48), ('levenes test', 48), ('gradient', 48), ('geometric distribution', 47), ('eviews', 47), ('lsmeans', 47), ('fuzzy', 47), ('density estimation', 46), ('minitab', 46), ('type ii errors', 46), ('robust standard error', 46), ('agreement statistics', 46), ('path model', 46), ('multivariable', 45), ('combining p values', 45), ('model based clustering', 45), ('programming', 45), ('arithmetic', 45), ('word embeddings', 44), ('geometry', 44), ('replication', 44), ('split plot', 44), ('gini', 44), ('microarray', 44), ('blocking', 44), ('rejection sampling', 43), ('macroeconomics', 43), ('constrained regression', 43), ('log likelihood', 43), ('multiarmed bandit', 42), ('code', 42), ('change scores', 42), ('imbalanced', 42), ('brownian', 42), ('clogit', 42), ('conjoint analysis', 42), ('univariate', 42), ('mixed design', 42), ('arch', 41), ('lavaan', 41), ('application', 41), ('jmp', 41), ('conditioning', 41), ('communication', 40), ('z statistic', 40), ('barplot', 40), ('semi supervised', 40), ('measure theory', 40), ('summations', 40), ('data cleaning', 40), ('tables', 39), ('impulse response', 39), ('demography', 39), ('generative models', 39), ('f distribution', 39), ('functional data analysis', 38), ('dlm', 38), ('sentiment analysis', 38), ('curves', 38), ('reproducible research', 38), ('c++', 38), ('back transformation', 38), ('logrank', 37), ('fat tails', 37), ('survey weights', 37), ('umvue', 37), ('mlogit', 37), ('package', 37), ('friedman test', 37), ('plm', 37), ('wavelet', 37), ('fractional factorial', 37), ('uninformative prior', 35), ('cauchy', 35), ('law of large numbers', 35), ('kriging', 35), ('marginal effect', 35), ('signed rank test', 34), ('lars', 34), ('bias correction', 34), ('mathematica', 34), ('formula', 34), ('ica', 34), ('valuation', 33), ('discontinuity', 33), ('projection', 33), ('multiple seasonalities', 33), ('hauck donner effect', 33), ('cosine similarity', 33), ('rotation', 33), ('census', 32), ('heterogeneity', 32), ('dendrogram', 32), ('biplot', 32), ('cholesky', 32), ('radial basis', 32), ('interval censoring', 32), ('error message', 31), ('careers', 31), ('crossover study', 31), ('numpy', 31), ('softmax', 31), ('rule of thumb', 31), ('real time', 31), ('f statistic', 31), ('mplus', 31), ('two way', 31), ('factor rotation', 31), ('anderson darling', 31), ('ecdf', 31), ('web', 31), ('parallel computing', 30), ('piecewise linear', 30), ('igraph', 30), ('oversampling', 30), ('range', 30), ('adaboost', 30), ('dataframe', 30), ('test for trend', 30), ('random matrix', 30), ('dispersion', 30), ('inverse gamma', 29), ('laplace distribution', 29), ('jaccard similarity', 29), ('e1071', 29), ('effects', 29), ('computing', 29), ('business intelligence', 29), ('incidence rate ratio', 29), ('bayes factors', 29), ('heavy tailed', 29), ('errors in variables', 29), ('heckman', 28), ('neyman pearson lemma', 28), ('transition matrix', 28), ('quasi likelihood', 28), ('discriminant', 28), ('model averaging', 28), ('frailty', 28), ('sphericity', 28), ('chemometrics', 28), ('statistical control', 28), ('constraint', 28), ('scale invariance', 28), ('stacking', 27), ('optimal scaling', 27), ('vc dimension', 27), ('social science', 27), ('k medoids', 27), ('moving window', 27), ('indicator variables', 27), ('tolerance interval', 26), ('poisson binomial', 26), ('conditional random field', 26), ('non response', 26), ('correlated predictors', 26), ('nnet', 26), ('apriori', 26), ('spark mllib', 26), ('tbats', 26), ('chow test', 26), ('segmented regression', 26), ('coding', 25), ('total least squares', 25), ('profile likelihood', 25), ('theano', 25), ('interaction variable', 25), ('control chart', 25), ('truncated normal', 25), ('mad', 25), ('cosine distance', 25), ('information', 24), ('big data', 24), ('partial', 24), ('concordance', 24), ('jackknife', 24), ('dropout', 24), ('rapidminer', 24), ('units', 24), ('churn', 24), ('qualitative', 24), ('survey sampling', 24), ('precision', 24), ('trimmed mean', 24), ('time complexity', 23), ('correlation matrix', 23), ('probabilistic programming', 23), ('ecm', 23), ('repeatability', 23), ('leverage', 23), ('subsampling', 23), ('funnel plot', 23), ('convex', 23), ('dunn test', 23), ('jeffreys prior', 23), ('kde', 23), ('sql', 23), ('gumbel', 23), ('characteristic function', 23), ('age', 23), ('representative', 23), ('bimodal', 22), ('skew normal', 22), ('compositional data', 22), ('presentation', 22), ('neuroscience', 22), ('pandas', 22), ('interactive visualization', 22), ('neweywest', 22), ('integration', 22), ('causalimpact', 21), ('finite mixture model', 21), ('non central', 21), ('synthetic data', 21), ('paradox', 21), ('ergodic', 21), ('zero inflated', 21), ('capture mark recapture', 21), ('events', 21), ('sequential pattern mining', 21), ('two step estimation', 21), ('choice', 21), ('geometric mean', 21), ('neuroimaging', 21), ('martingale', 20), ('symmetry', 20), ('c#', 20), ('deming regression', 20), ('optimal stopping', 20), ('publication bias', 20), ('familywise error', 20), ('simpsons paradox', 20), ('interarrival time', 20), ('multivariate distribution', 20), ('taylor series', 20), ('hotelling', 20), ('failure', 20), ('average precision', 20), ('cost maximization', 20), ('determinant', 20), ('project management', 20), ('mancova', 20), ('polling', 19), ('nonparametric regression', 19), ('language models', 19), ('matplotlib', 19), ('compression', 19), ('coverage probability', 19), ('abc', 19), ('competing risks', 19), ('singular', 19), ('bernoulli process', 19), ('fraud', 19), ('box jenkins', 19), ('nnmf', 19), ('decomposition', 19), ('xgboost', 19), ('standard', 19), ('cross entropy', 19), ('elasticity', 19), ('database', 18), ('operations research', 18), ('variance decomposition', 18), ('phylogeny', 18), ('scoring rules', 18), ('hessian', 18), ('differences', 18), ('tsne', 18), ('zipf', 18), ('pivot', 17), ('non nested', 17), ('data association', 17), ('cfa', 17), ('directional statistics', 17), ('overlapping data', 17), ('steins phenomenon', 17), ('recurrent events', 17), ('sign test', 17), ('heatmap', 17), ('planned comparisons test', 17), ('fisher transform', 17), ('academia', 17), ('dbscan', 17), ('tost', 17), ('proportional hazards', 16), ('underdispersion', 16), ('open bugs', 16), ('manifold learning', 16), ('fuzzy set', 16), ('one class', 16), ('linearity', 16), ('coupon collector problem', 16), ('sandwich', 16), ('mape', 16), ('cramers v', 16), ('reml', 16), ('index decomposition', 15), ('gis', 15), ('inequality', 15), ('rbf network', 15), ('heuristic', 15), ('gamm4', 15), ('lrt', 15), ('matrix calculus', 15), ('dependence', 15), ('climate', 15), ('extrapolation', 15), ('rasch', 15), ('dag', 15), ('fractal', 15), ('exact test', 15), ('mortality', 15)

In [32]:
common_tags=list(freq.keys())[:10]
common_tags

['r',
 'regression',
 'machine learning',
 'time series',
 'probability',
 'hypothesis testing',
 'self study',
 'distributions',
 'logistic',
 'classification']

In [33]:
x=[]
y=[]

for i in range(len(df['tags'])):
    temp=[]
    for j in df['tags'][i]:
        if j in common_tags:
          temp.append(j)   
    if (len(temp)>1):
        x.append(df['cleaned_text'][i])
        y.append(temp)

In [34]:
len(x)

11106

In [35]:
x[:5]

[' i recently started working for a tuberculosis clinic we meet periodically to discuss the number of tb cases we re currently treating the number of tests administered etc i d like to start modeling these counts so that we re not just guessing whether something is unusual or not unfortunately i ve had very little training in time series and most of my exposure has been to models for very continuous data stock prices or very large numbers of counts influenza but we deal with cases per month mean median var which are distributed like this image lost to the mists of time image eaten by a grue i ve found a few articles that address models like this but i d greatly appreciate hearing suggestions from you both for approaches and for r packages that i could use to implement those approaches edit mbq s answer has forced me to think more carefully about what i m asking here i got too hung up on the monthly counts and lost the actual focus of the question what i d like to know is does the fairly visible decline from say onward reflect a downward trend in the overall number of cases it looks to me like the number of cases monthly from reflects a stable process maybe some seasonality but overall stable from through the present it looks like that process is changing the overall number of cases is declining even though the monthly counts might wobble up and down due to randomness and seasonality how can i test if there s a real change in the process and if i can identify a decline how could i use that trend and whatever seasonality there might be to estimate the number of cases we might see in the upcoming months whew thanks for bearing with me ',
 ' am i looking for a better behaved distribution for the independent variable in question or to reduce the effect of outliers or something else ',
 ' there are many ways to measure how similar two probability distributions are among methods which are popular in different circles are the kolmogorov distance the sup distance between the distribution functions the kantorovich rubinstein distance the maximum difference between the expectations w r t the two distributions of functions with lipschitz constant which also turns out to be the l distance between the distribution functions the bounded lipschitz distance like the k r distance but the functions are also required to have absolute value at most these have different advantages and disadvantages only convergence in the sense of actually corresponds precisely to convergence in distribution convergence in the sense of or is slightly stronger in general in particular if x n frac n with probability then x n converges to in distribution but not in the kolmogorov distance however if the limit distribution is continuous then this pathology doesn t occur from the perspective of elementary probability or measure theory is very natural because it compares the probabilities of being in some set a more sophisticated probabilistic perspective on the other hand tends to focus more on expectations than probabilities also from the perspective of functional analysis distances like or based on duality with some function space are very appealing because there is a large set of mathematical tools for working with such things however my impression correct me if i m wrong is that in statistics the kolmogorov distance is the usually preferred way of measuring similarity of distributions i can guess one reason if one of the distributions is discrete with finite support in particular if it is the distribution of some real world data then the kolmogorov distance to a model distribution is easy to compute the k r distance would be slightly harder to compute and the b l distance would probably be impossible in practical terms so my question finally is are there other reasons either practical or theoretical to favor the kolmogorov distance or some other distance for statistical purposes ',
 ' a lab has been asked to evaluate the claim that drinking water in a local restaurant has a lead concentration of parts per billion ppb repeated measurements follow a normal distribution and the population standard deviation is taken to be ppb a sample of three measurements is taken and finds is there evidence to suggest that the lead concentration is different from ppb this is a homework question that i m really stuck on so if someone could point me in the right direction that would be great i realise that it is a hypothesis testing question and that the null hypothesis is that ppb while the alternative is that does not equal ppb however i really don t know what to do with the three sample measurements do i get the mean of the three figures or do i use each in a separate hypothesis test ',
 ' how would we measure the predictive power of predictors in time series models for e g in linear regression we have the magnitude and direction of the regression co efficients and their p values is there any measure like that to evaluate the performance of predictors in kalman filter ']

In [36]:
y[:5]

[['r', 'time series'],
 ['regression', 'distributions'],
 ['distributions', 'probability', 'hypothesis testing'],
 ['hypothesis testing', 'self study'],
 ['r', 'regression', 'time series']]

In [37]:
from sklearn.preprocessing import MultiLabelBinarizer
mlb=MultiLabelBinarizer()
y=mlb.fit_transform(y)
y.shape

(11106, 10)

In [38]:
y[0,:]

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 1])

In [39]:
mlb.classes_

array(['classification', 'distributions', 'hypothesis testing',
       'logistic', 'machine learning', 'probability', 'r', 'regression',
       'self study', 'time series'], dtype=object)

In [40]:
from sklearn.model_selection import train_test_split
x_tr,x_val,y_tr,y_val=train_test_split(x,y,test_size=0.2,random_state=0, shuffle=True)

In [41]:
print("x_tr:", len(x_tr), "y_tr:", len(y_tr))
print("x_val:",len(x_val), "y_val:", len(y_val))

x_tr: 8884 y_tr: 8884
x_val: 2222 y_val: 2222

In [42]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [43]:
word_vectorizer=TfidfVectorizer(max_features=5000)

In [44]:
word_vectorizer.fit(x_tr)

TfidfVectorizer(max_features=5000)

In [45]:
train_word_features=word_vectorizer.transform(x_tr)

In [46]:
train_word_features

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 689105 stored elements and shape (8884, 5000)>

In [47]:
test_word_features=word_vectorizer.transform(x_val)
test_word_features

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 169720 stored elements and shape (2222, 5000)>

In [48]:
from sklearn.multiclass import OneVsRestClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import f1_score

In [49]:
nb_model=OneVsRestClassifier(MultinomialNB())

In [50]:
nb_model.fit(train_word_features,y_tr)

OneVsRestClassifier(estimator=MultinomialNB())

In [71]:
train_pred_nb = nb_model.predict_proba(train_word_features)

In [73]:
train_pred_nb[:5]

array([[0.01344724, 0.03740482, 0.28222978, 0.02697458, 0.01633795,
        0.02506567, 0.89538969, 0.12073754, 0.0700849 , 0.9171051 ],
       [0.00998546, 0.0110149 , 0.02463366, 0.07908787, 0.02420268,
        0.01546075, 0.42975165, 0.6741038 , 0.01497687, 0.39696457],
       [0.06333453, 0.02789201, 0.0424841 , 0.2655143 , 0.09664726,
        0.0317234 , 0.34204464, 0.59332859, 0.04190282, 0.0376353 ],
       [0.0256477 , 0.02181011, 0.06350088, 0.04377451, 0.08734494,
        0.01908054, 0.58005273, 0.35855072, 0.05014792, 0.58172381],
       [0.00645846, 0.0017878 , 0.00359254, 0.00911818, 0.03907929,
        0.00232402, 0.92296367, 0.16261188, 0.00382148, 0.98254765]])

In [77]:
def classify(pred_prob, threshold):
    return (pred_prob >= threshold).astype(int)

In [78]:
import numpy as np
from sklearn.metrics import f1_score

def optimum_threshold(actual, pred_prob):
    thresholds = np.arange(0, 0.5, 0.1)  # from 0 to 0.5

    score = []
    
    for value in thresholds:
        pred_classes = classify(pred_prob, value)
        score.append(f1_score(actual, pred_classes, average="weighted"))
        
    return thresholds[score.index(max(score))]

In [79]:
print("Optimal Threshold=>", optimum_threshold(y_tr, train_pred_nb))

Optimal Threshold=> 0.30000000000000004

In [80]:
train_pred_nb_class=classify(train_pred_nb, 0.30)

In [81]:
train_pred_nb_class[:5]

array([[0, 0, 0, 0, 0, 0, 1, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 1]])

In [83]:
mlb.inverse_transform(np.array(train_pred_nb_class[:5]))

[('r', 'time series'),
 ('r', 'regression', 'time series'),
 ('r', 'regression'),
 ('r', 'regression', 'time series'),
 ('r', 'time series')]

In [86]:
print("f1-score on train-set:",f1_score(y_tr,train_pred_nb_class,average="weighted"))

f1-score on train-set: 0.7173779844739174

In [87]:
val_pred_nb=nb_model.predict_proba(test_word_features)

In [88]:
val_pred_nb_class=classify(val_pred_nb,0.30)

In [89]:
print("f1-score on validation set:", f1_score(y_val,val_pred_nb_class, average="weighted"))

f1-score on validation set: 0.6471715961995358

In [90]:
from sklearn.linear_model import LogisticRegression

In [93]:
lr_model=OneVsRestClassifier(LogisticRegression())
lr_model.fit(train_word_features, y_tr)

OneVsRestClassifier(estimator=LogisticRegression())

In [95]:
train_pred_lr=lr_model.predict_proba(train_word_features)

In [96]:
train_pred_lr[:5]

array([[0.019655  , 0.03355877, 0.27107585, 0.03275855, 0.02303131,
        0.02489797, 0.90555739, 0.12760037, 0.04931186, 0.65955848],
       [0.02274497, 0.03116318, 0.09357807, 0.08456416, 0.03927476,
        0.03656584, 0.4139801 , 0.85330895, 0.05036709, 0.50195913],
       [0.07891207, 0.02846155, 0.04503306, 0.24182428, 0.10834637,
        0.03246708, 0.63254943, 0.81833722, 0.04548671, 0.0651938 ],
       [0.01567344, 0.01305426, 0.40801349, 0.0418786 , 0.08837533,
        0.0058441 , 0.64418692, 0.41407137, 0.03528106, 0.58271905],
       [0.0308317 , 0.00683419, 0.01773856, 0.03878678, 0.08578545,
        0.00753684, 0.9235889 , 0.24798212, 0.01633365, 0.93859518]])

In [97]:
print("Optimal Threshold=>", optimum_threshold(y_tr,train_pred_lr))

Optimal Threshold=> 0.30000000000000004

In [98]:
train_pred_lr_class=classify(train_pred_lr,0.300004)

In [99]:
train_pred_lr_class[:5]

array([[0, 0, 0, 0, 0, 0, 1, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 1, 0, 0],
       [0, 0, 1, 0, 0, 0, 1, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 1]])

In [101]:
print("F1-score on train set:", f1_score(y_tr, train_pred_lr_class,average="weighted"))

F1-score on train set: 0.8244114965777203

In [105]:
val_pred_lr=lr_model.predict_proba(test_word_features)

In [106]:
val_pred_lr_class=classify(val_pred_lr,0.30)

In [107]:
print("F1-score on Validation set:", f1_score(y_val,val_pred_lr_class,average="weighted"))

F1-score on Validation set: 0.7536380833989702

In [113]:
def tagging(question):
    cleaned_question=basic_clean(question)
    vector=word_vectorizer.transform([cleaned_question])
    pred_prob=lr_model.predict_proba(vector)
    pred_class=classify(pred_prob,0.300004)

    return mlb.inverse_transform(np.array(pred_class))

In [120]:
import numpy as np
all_tags = mlb.classes_
def tagging(question, top_k=3):
    cleaned_question = basic_clean(question)

    vector = word_vectorizer.transform([cleaned_question])
    pred_prob = lr_model.predict_proba(vector)

    probs = pred_prob[0]

    top_indices = np.argsort(probs)[-top_k:]
    tags = [all_tags[i] for i in top_indices]

    return tags

In [124]:
tagging("<p>How would you describe in plain English the characteristics that distinguish Bayesian from Frequentist reasoning?</p>\n")

['r', 'self study', 'probability']

In [125]:
import pickle

pickle.dump(lr_model, open("lr_model.pkl", "wb"))
pickle.dump(word_vectorizer, open("vectorizer.pkl", "wb"))
pickle.dump(mlb, open("mlb.pkl", "wb"))